feat(ci): add composer audit to CI pipeline (#1031)

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -13,6 +13,61 @@ permissions:
 env:
   FRANKENPHP_VERSION: v1.11.2
   ROADRUNNER_VERSION: v2025.1.7
+  COMPOSER_ADVISORY_SYMFONY_COMMON: >-
+    [
+      "PKSA-z7t6-zt6p-wtng",
+      "PKSA-5r1g-c7b7-y1zg",
+      "PKSA-4k7v-pfvw-nqvp",
+      "PKSA-365x-2zjk-pt47",
+      "PKSA-b35n-565h-rs4q",
+      "PKSA-4wjj-gy1p-ft3r",
+      "PKSA-wws7-mr54-jsny",
+      "PKSA-bf7t-jnpz-492k",
+      "PKSA-yc7t-91v9-99xs",
+      "PKSA-c28x-6bj5-8spx",
+      "PKSA-tbsf-h7vc-j7hn",
+      "PKSA-v5yj-8nmz-sk2q",
+      "PKSA-ft77-7h5f-p3r6",
+      "PKSA-b14r-zh1d-vdrc"
+    ]
+  COMPOSER_ADVISORY_SYMFONY_4_4_AND_5_LOWEST: >-
+    [
+      "PKSA-wtxr-p26d-nn42",
+      "PKSA-2n2k-66v2-bwg3",
+      "PKSA-rkkf-636k-qjb3"
+    ]
+  COMPOSER_ADVISORY_SYMFONY_5_LOWEST_AND_6: >-
+    [
+      "PKSA-ztgh-x9c8-k66g"
+    ]
+  COMPOSER_ADVISORY_SYMFONY_5_LOWEST_ONLY: >-
+    [
+      "PKSA-hr4y-jwk2-1yb9",
+      "PKSA-8knv-7jsn-12w8"
+    ]
+  COMPOSER_ADVISORY_SYMFONY_6_PHP_8_0_ONLY: >-
+    [
+      "PKSA-rqvm-b18n-vg69",
+      "PKSA-5x8m-77gx-t86z"
+    ]
+  COMPOSER_ADVISORY_TWIG: >-
+    [
+      "PKSA-fbvq-z33h-r2np",
+      "PKSA-g9zw-qxh8-pq8w",
+      "PKSA-yd6k-t2gh-1m43",
+      "PKSA-1tmc-rt7x-12w6",
+      "PKSA-xx6c-6d96-db2w",
+      "PKSA-sjvz-tbbr-vwth",
+      "PKSA-h8hf-ytnd-5t9q",
+      "PKSA-kvv6-36cr-fkzb",
+      "PKSA-n14z-jjjg-g8vd",
+      "PKSA-3mcc-k66d-pydb",
+      "PKSA-dpx1-78wg-1kqs",
+      "PKSA-yhcn-xrg3-68b1",
+      "PKSA-2wrf-1xmk-1pky",
+      "PKSA-6319-ffpf-gx66",
+      "PKSA-n7sg-8f52-pqtf"
+    ]
 
 jobs:
   tests:
@@ -121,11 +176,51 @@ jobs:
         if: ${{ matrix.dependencies == 'lowest' && matrix.php != '7.2' }}
         run: composer require phpunit/phpunit:^9.6.34 --dev --no-interaction --no-update
 
+        # The following tasks add security advisories to the allowlist to allow proper composer resolution
+        # They are as strict as possible and bound to particular versions so that we only ignore a well known set.
+        # If new ones appear, they will fail CI and will require investigation
+        # The rationale behind that is that we don't want to ignore them for all versions and instead only
+        # ignore them if absolutely necessary for resolution so that composer can select versions without security
+        # concerns if available
+      - name: Configure common Symfony advisory allowlist
+        if: ${{ matrix.symfony-version == '4.4.*' || (matrix.symfony-version == '5.*' && matrix.php == '7.2' && matrix.dependencies == 'lowest') || (matrix.symfony-version == '6.*' && matrix.php == '8.0') }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_COMMON"
+
+      - name: Configure Symfony 4.4/5 lowest advisory allowlist
+        if: ${{ matrix.symfony-version == '4.4.*' || (matrix.symfony-version == '5.*' && matrix.php == '7.2' && matrix.dependencies == 'lowest') }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_4_4_AND_5_LOWEST"
+
+      - name: Configure Symfony 5 lowest/6 advisory allowlist
+        if: ${{ (matrix.symfony-version == '5.*' && matrix.php == '7.2' && matrix.dependencies == 'lowest') || (matrix.symfony-version == '6.*' && matrix.php == '8.0') }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_5_LOWEST_AND_6"
+
+      - name: Configure Symfony 5 lowest advisory allowlist
+        if: ${{ matrix.symfony-version == '5.*' && matrix.php == '7.2' && matrix.dependencies == 'lowest' }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_5_LOWEST_ONLY"
+
+      - name: Configure Symfony 6 advisory allowlist
+        if: ${{ matrix.symfony-version == '6.*' && matrix.php == '8.0' }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_6_PHP_8_0_ONLY"
+
+      - name: Configure Twig advisory allowlist
+        if: ${{ contains(fromJSON('["4.4.*","5.*","6.*"]'), matrix.symfony-version) && contains(fromJSON('["7.2","7.3","7.4","8.0"]'), matrix.php) }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_TWIG"
+
+      # End of security advisory tasks
+
+      - name: Resolve dependencies
+        run: composer update --no-progress --no-interaction --prefer-dist --no-install --no-scripts --no-audit
+        if: ${{ matrix.dependencies == 'highest' }}
+
+      - name: Resolve dependencies
+        run: composer update --no-progress --no-interaction --prefer-dist --prefer-lowest --no-install --no-scripts --no-audit
+        if: ${{ matrix.dependencies == 'lowest' }}
+
+      - name: Audit dependencies
+        run: composer audit --locked --no-interaction --format=table --abandoned=report
+
       - name: Install dependencies
-        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v3
-        with:
-          dependency-versions: ${{ matrix.dependencies }}
-          composer-options: --prefer-dist --no-security-blocking
+        run: composer install --no-progress --no-interaction --prefer-dist --no-scripts
 
       - name: Run tests
         run: vendor/bin/phpunit --coverage-clover=build/coverage-report.xml
@@ -186,11 +281,51 @@ jobs:
         if: ${{ matrix.dependencies == 'lowest' && matrix.php != '7.2' }}
         run: composer require phpunit/phpunit:^9.6.34 --dev --no-interaction --no-update
 
+      # The following tasks add security advisories to the allowlist to allow proper composer resolution
+      # They are as strict as possible and bound to particular versions so that we only ignore a well known set.
+      # If new ones appear, they will fail CI and will require investigation
+      # The rationale behind that is that we don't want to ignore them for all versions and instead only
+      # ignore them if absolutely necessary for resolution so that composer can select versions without security
+      # concerns if available
+      - name: Configure common Symfony advisory allowlist
+        if: ${{ matrix.symfony-version == '4.4.*' || (matrix.symfony-version == '5.*' && matrix.php == '7.2' && matrix.dependencies == 'lowest') || (matrix.symfony-version == '6.*' && matrix.php == '8.0') }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_COMMON"
+
+      - name: Configure Symfony 4.4/5 lowest advisory allowlist
+        if: ${{ matrix.symfony-version == '4.4.*' || (matrix.symfony-version == '5.*' && matrix.php == '7.2' && matrix.dependencies == 'lowest') }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_4_4_AND_5_LOWEST"
+
+      - name: Configure Symfony 5 lowest/6 advisory allowlist
+        if: ${{ (matrix.symfony-version == '5.*' && matrix.php == '7.2' && matrix.dependencies == 'lowest') || (matrix.symfony-version == '6.*' && matrix.php == '8.0') }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_5_LOWEST_AND_6"
+
+      - name: Configure Symfony 5 lowest advisory allowlist
+        if: ${{ matrix.symfony-version == '5.*' && matrix.php == '7.2' && matrix.dependencies == 'lowest' }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_5_LOWEST_ONLY"
+
+      - name: Configure Symfony 6 advisory allowlist
+        if: ${{ matrix.symfony-version == '6.*' && matrix.php == '8.0' }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_SYMFONY_6_PHP_8_0_ONLY"
+
+      - name: Configure Twig advisory allowlist
+        if: ${{ contains(fromJSON('["4.4.*","5.*","6.*"]'), matrix.symfony-version) && contains(fromJSON('["7.2","7.3","7.4","8.0"]'), matrix.php) }}
+        run: composer config --merge --json policy.advisories.ignore-id "$COMPOSER_ADVISORY_TWIG"
+
+    # End of security advisory tasks
+
+      - name: Resolve dependencies
+        run: composer update --no-progress --no-interaction --prefer-dist --no-install --no-scripts --no-audit
+        if: ${{ matrix.dependencies == 'highest' }}
+
+      - name: Resolve dependencies
+        run: composer update --no-progress --no-interaction --prefer-dist --prefer-lowest --no-install --no-scripts --no-audit
+        if: ${{ matrix.dependencies == 'lowest' }}
+
+      - name: Audit dependencies
+        run: composer audit --locked --no-interaction --format=table --abandoned=report
+
       - name: Install dependencies
-        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v3
-        with:
-          dependency-versions: ${{ matrix.dependencies }}
-          composer-options: --prefer-dist --no-security-blocking
+        run: composer install --no-progress --no-interaction --prefer-dist --no-scripts
 
       - name: Run tests
         run: vendor/bin/phpunit --coverage-clover=build/coverage-report.xml
@@ -229,8 +364,14 @@ jobs:
           key: ${{ runner.os }}-runtime-frankenphp-composer-${{ hashFiles('**/composer.lock') }}
           restore-keys: ${{ runner.os }}-runtime-frankenphp-composer-
 
+      - name: Resolve dependencies
+        run: composer update --no-progress --no-interaction --prefer-dist --no-install --no-scripts --no-audit
+
+      - name: Audit dependencies
+        run: composer audit --locked --no-interaction --format=table --abandoned=report
+
       - name: Install dependencies
-        run: composer install --no-progress --no-interaction --prefer-dist
+        run: composer install --no-progress --no-interaction --prefer-dist --no-scripts
 
       - name: Install FrankenPHP
         env:
@@ -294,8 +435,14 @@ jobs:
           key: ${{ runner.os }}-runtime-roadrunner-composer-${{ hashFiles('**/composer.lock') }}
           restore-keys: ${{ runner.os }}-runtime-roadrunner-composer-
 
+      - name: Resolve dependencies
+        run: composer update --no-progress --no-interaction --prefer-dist --no-install --no-scripts --no-audit
+
+      - name: Audit dependencies
+        run: composer audit --locked --no-interaction --format=table --abandoned=report
+
       - name: Install dependencies
-        run: composer install --no-progress --no-interaction --prefer-dist
+        run: composer install --no-progress --no-interaction --prefer-dist --no-scripts
 
       - name: Install RoadRunner
         env:
